<a href="https://colab.research.google.com/github/richa-giri/IT-Helpdesk-Analytics/blob/main/SQLite_Database.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# SQL Analysis for IT Helpdesk Ticket Analytics

### SQLite | SQL Queries

## Project Objective

This notebook imports the cleaned IT helpdesk dataset into SQLite and performs SQL queries to answer common business questions.

In [25]:
from google.colab import files

uploaded = files.upload()

Saving cleaned_ticket.csv to cleaned_ticket.csv

In [26]:
import pandas as pd
import sqlite3

In [27]:
df = pd.read_csv("cleaned_ticket.csv")

## Load Cleaned Dataset

In [28]:
df.head()

,Ticket_ID,Body,Department,Priority,Tags
0,0,"Dear Customer Support Team,I am writing to rep...",Technical Support,high,"['Account', 'Disruption', 'Outage', 'IT', 'Tec..."
1,1,"Dear Customer Support Team,I hope this message...",Returns and Exchanges,medium,"['Product', 'Feature', 'Tech Support']"
2,2,"Dear Customer Support Team,I hope this message...",Billing and Payments,low,"['Billing', 'Payment', 'Account', 'Documentati..."
3,3,"Dear Support Team,I hope this message reaches ...",Sales and Pre-Sales,medium,"['Product', 'Feature', 'Feedback', 'Tech Suppo..."
4,4,"Dear Customer Support,I hope this message reac...",Technical Support,high,"['Feature', 'Product', 'Documentation', 'Feedb..."

In [30]:
conn = sqlite3.connect("helpdesk.db")

In [31]:
df.to_sql(
    "Tickets",
    conn,
    if_exists="replace",
    index=False
)

29651

## Query 1: Display the First Five Records

In [32]:
query = """
SELECT *
FROM Tickets
LIMIT 5;
"""

pd.read_sql(query, conn)

,Ticket_ID,Body,Department,Priority,Tags
0,0,"Dear Customer Support Team,I am writing to rep...",Technical Support,high,"['Account', 'Disruption', 'Outage', 'IT', 'Tec..."
1,1,"Dear Customer Support Team,I hope this message...",Returns and Exchanges,medium,"['Product', 'Feature', 'Tech Support']"
2,2,"Dear Customer Support Team,I hope this message...",Billing and Payments,low,"['Billing', 'Payment', 'Account', 'Documentati..."
3,3,"Dear Support Team,I hope this message reaches ...",Sales and Pre-Sales,medium,"['Product', 'Feature', 'Feedback', 'Tech Suppo..."
4,4,"Dear Customer Support,I hope this message reac...",Technical Support,high,"['Feature', 'Product', 'Documentation', 'Feedb..."

## Query 2: Count Total Number of Tickets

In [33]:
query = """
SELECT COUNT(*) AS Total_Tickets
FROM Tickets;
"""

pd.read_sql(query, conn)

   Total_Tickets
0          29651

## Query 3: Count Tickets by Department

In [34]:
query = """
SELECT Department,
COUNT(*) AS Total_Tickets

FROM Tickets

GROUP BY Department

ORDER BY Total_Tickets DESC;
"""

pd.read_sql(query, conn)

                        Department  Total_Tickets
0                Technical Support           8617
1                  Product Support           5539
2                 Customer Service           4482
3                       IT Support           3500
4             Billing and Payments           3017
5            Returns and Exchanges           1467
6  Service Outages and Maintenance           1157
7              Sales and Pre-Sales            885
8                  Human Resources            568
9                  General Inquiry            419

## Query 4: Count Tickets by Priority

In [35]:
query = """
SELECT Priority,
COUNT(*) AS Total

FROM Tickets

GROUP BY Priority

ORDER BY Total DESC;
"""

pd.read_sql(query, conn)

  Priority  Total
0   medium  12126
1     high  11512
2      low   6013

## Query 5: Display High-Priority Tickets

In [36]:
query = """
SELECT *
FROM Tickets
WHERE Priority='high';
"""

pd.read_sql(query, conn)

,Ticket_ID,Body,Department,Priority,Tags
0,0,"Dear Customer Support Team,I am writing to rep...",Technical Support,high,"['Account', 'Disruption', 'Outage', 'IT', 'Tec..."
1,4,"Dear Customer Support,I hope this message reac...",Technical Support,high,"['Feature', 'Product', 'Documentation', 'Feedb..."
2,5,"Dear Customer Support Team,I am submitting a r...",Service Outages and Maintenance,high,"['Outage', 'Disruption', 'Performance', 'IT', ..."
3,9,"Dear Customer Support Team,I hope this message...",Product Support,high,"['Product', 'Service', 'Feedback', 'Sales']"
4,12,"Dear Customer Support Team,I am reaching out t...",Technical Support,high,"['Feature', 'Account', 'Marketing', 'Performan..."
...,...,...,...,...,...
11507,29646,"Hello Customer Support Team,My name is name. I...",IT Support,high,"['Technical Support', 'Urgent Issue', 'Service..."
11508,29647,"Dear Customer Support Team,We are currently en...",IT Support,high,"['Service Disruption', 'IT Support', 'Urgent I..."
11509,29648,"Dear Customer Support Team,Our Cisco Router IS...",Technical Support,high,"['Technical Support', 'Network Issue', 'Urgent..."
11510,29649,"Dear IT Services Support Team, I am writing to...",Technical Support,high,"['Urgent Issue', 'Service Disruption', 'Incide..."
11511,29650,"Dear Tech Online Store Customer Support,I rece...",Billing and Payments,high,"['Billing Issue', 'Customer Service', 'Account..."

## Query 6: Display Low-Priority Tickets

In [37]:
query = """
SELECT *
FROM Tickets
WHERE Priority='low';
"""

pd.read_sql(query, conn)

,Ticket_ID,Body,Department,Priority,Tags
0,2,"Dear Customer Support Team,I hope this message...",Billing and Payments,low,"['Billing', 'Payment', 'Account', 'Documentati..."
1,21,"Dear Customer Support Team,I am reaching out t...",Technical Support,low,"['Hardware', 'Tech Support', 'Driver', 'Audio']"
2,25,"Dear Customer Support Team,I hope this message...",Technical Support,low,"['Documentation', 'Feature', 'IT', 'Tech Suppo..."
3,26,"Dear Customer Support Team,I hope this message...",Customer Service,low,"['Network', 'Disruption', 'Connectivity', 'Tec..."
4,27,"Dear Customer Support Team,I hope this message...",Billing and Payments,low,"['Billing', 'Payment', 'Dispute', 'Documentati..."
...,...,...,...,...,...
6008,29616,"Dear Customer Support Team,I hope this message...",Technical Support,low,"['Technical Support', 'Product Support', 'Soft..."
6009,29623,"Hello Customer Support,I am reaching out to re...",IT Support,low,"['Technical Support', 'IT Support', 'Product S..."
6010,29625,"Dear Customer Support Team, I hope this messag...",IT Support,low,"['Technical Support', 'Product Support', 'Soft..."
6011,29643,"Dear Customer Service, The Human Resources dep...",Human Resources,low,"['Consulting Services', 'IT Support', 'Human R..."
6012,29644,The customer seeks changes in their IT infrast...,Customer Service,low,"['IT Support', 'Technical Support', 'Product S..."

## Query 7: Department-wise Priority Distribution

In [38]:
query = """
SELECT Department,
Priority,
COUNT(*) AS Total

FROM Tickets

GROUP BY Department, Priority

ORDER BY Department;
"""

pd.read_sql(query, conn)

                         Department Priority  Total
0              Billing and Payments     high    886
1              Billing and Payments      low    632
2              Billing and Payments   medium   1499
3                  Customer Service     high    828
4                  Customer Service      low   1464
5                  Customer Service   medium   2190
6                   General Inquiry     high     66
7                   General Inquiry      low    246
8                   General Inquiry   medium    107
9                   Human Resources     high     59
10                  Human Resources      low    271
11                  Human Resources   medium    238
12                       IT Support     high   1657
13                       IT Support      low    347
14                       IT Support   medium   1496
15                  Product Support     high   1682
16                  Product Support      low   1048
17                  Product Support   medium   2809
18            Returns and Exchanges     high    328
19            Returns and Exchanges      low    546
20            Returns and Exchanges   medium    593
21              Sales and Pre-Sales     high    154
22              Sales and Pre-Sales      low    323
23              Sales and Pre-Sales   medium    408
24  Service Outages and Maintenance     high    818
25  Service Outages and Maintenance      low    143
26  Service Outages and Maintenance   medium    196
27                Technical Support     high   5034
28                Technical Support      low    993
29                Technical Support   medium   2590

## Query 8: Department with the Highest Number of Tickets

In [39]:
query = """
SELECT Department,
COUNT(*) AS Tickets

FROM Tickets

GROUP BY Department

ORDER BY Tickets DESC

LIMIT 1;
"""

pd.read_sql(query, conn)

          Department  Tickets
0  Technical Support     8617

## Query 9: Count Total Departments

In [17]:
query = """
SELECT COUNT(DISTINCT Department) AS Total_Departments
FROM Tickets;
"""

pd.read_sql(query, conn)

   Total_Departments
0                 10

## Query 10: Priority-wise Ticket Count

In [40]:
query = """
SELECT Priority,
COUNT(*) AS Total

FROM Tickets

GROUP BY Priority;
"""

pd.read_sql(query, conn)

  Priority  Total
0     high  11512
1      low   6013
2   medium  12126

In [41]:
department_sql = pd.read_sql("""
SELECT Department,
COUNT(*) AS Total_Tickets

FROM Tickets

GROUP BY Department
ORDER BY Total_Tickets DESC;
""", conn)

department_sql.to_csv("department_sql.csv", index=False)

# SQL Summary

The SQL queries confirmed the insights obtained from Python analysis.

### Key Findings

- Technical Support received the highest number of tickets.
- Medium-priority tickets were the most common.
- Ticket volume varies significantly across departments.

SQL provided an efficient way to summarize and retrieve business insights from the dataset.

In [42]:
from google.colab import files

files.download("department_sql.csv")

In [43]:
conn.close()